// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func OrnamentalBorder(position string, fixed bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		className := "frame-corner " + position + " animate-glow"
		if fixed {
			className = className + " is-fixed"
		} else {
			className = className + " is-flow"
		}
		var templ_7745c5c3_Var2 = []any{"frame-corner " + className + " animate-glow"}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/ornamental_border.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" viewBox=\"0 0 100 100\" fill=\"none\"><path d=\"\n          M4 96\n          Q4 40 40 40\n          Q72 40 72 8\n        \" stroke=\"#C8A44D\" stroke-width=\"2\"></path> <path d=\"\n          M18 82\n          Q18 55 40 55\n          Q58 55 58 24\n        \" stroke=\"#C46A2D\" stroke-width=\"1.5\"></path> <circle cx=\"72\" cy=\"8\" r=\"4\" fill=\"#C8A44D\"></circle> <circle cx=\"40\" cy=\"40\" r=\"3\" fill=\"#8C2F2F\"></circle> <path d=\"M40 30 Q44 36 40 40 Q36 36 40 30\" fill=\"#C46A2D\"></path> <path d=\"M50 40 Q44 44 40 40 Q44 36 50 40\" fill=\"#C46A2D\"></path> <path d=\"M40 50 Q36 44 40 40 Q44 44 40 50\" fill=\"#C46A2D\"></path> <path d=\"M30 40 Q36 36 40 40 Q36 44 30 40\" fill=\"#C46A2D\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
